### ISSUE TITLE
Please remove android:allowBackup from Manifest

### ISSUE THREAD

**Issue by schaal** [divStar/ico4a#1]
I'd like to set `android:allowBackup` to false, but due to a bug (https://code.google.com/p/android/issues/detail?id=70073) it's not possible to replace `android:allowBackup` in the app's AndroidManifest (even with `tools:replace="android:allowBackup"`)

Could you remove the statement from the library's Manifest so that the app can set the value by itself?

For reference this is the error when trying to override it:

```
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:35:9-36
    is also present at [divstar:ico4a:v1.0] AndroidManifest.xml:12:9-35 value=(true).
    Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:27:5-63:19 to override.
```

**Comment by divStar** [comment]
It's (apparently) not really an issue of the application. Nevertheless from what I have read about that key ("allowBackup"), I suppose removing it should not harm the library. Did you test it after you removed that line from the manifest?

**Comment by schaal** [comment]
I haven't tested it yet, but I had the same issue with another library and removing it from the library fixed it (https://github.com/realm/realm-java/issues/2227)

**Comment by schaal** [comment]
Ok, just tested it with a local build of ico4a without allowBackup, and it compiles and runs fine now.

**Comment by divStar** [comment]
Merged the solution you pushed. Thank you! Not sure a library should contain allowBackup anyway, but I guess now it does not.
